name: hello_world_cli
description: A sample CLI app integrating LangChain.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  langchain: ^0.7.7
  langchain_openai: ^0.7.2+1
