name: langchain_community
description: LangChain.dart third-party integrations that don't have a dedicated package.
version: 0.2.0+1
repository: https://github.com/davidmigloz/langchain_dart/tree/main/packages/langchain_community
issue_tracker: https://github.com/davidmigloz/langchain_dart/issues?q=label:p:langchain_community
homepage: https://github.com/davidmigloz/langchain_dart
documentation: https://langchaindart.com

topics:
  - ai
  - nlp
  - llms
  - langchain

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  beautiful_soup_dart: ^0.3.0
  cross_file: ^0.3.4+1
  csv: ^6.0.0
  http: ^1.1.0
  json_path: ^0.7.1
  langchain_core: ^0.3.1
  math_expressions: ^2.4.0
  meta: ^1.11.0

dev_dependencies:
  test: ^1.25.2
