name: langchain_community
description: LangChain.dart third-party integrations that don't have a dedicated package.
version: 0.3.4
repository: https://github.com/davidmigloz/langchain_dart/tree/main/packages/langchain_community
issue_tracker: https://github.com/davidmigloz/langchain_dart/issues?q=label:p:langchain_community
homepage: https://github.com/davidmigloz/langchain_dart
documentation: https://langchaindart.dev

funding:
  - https://github.com/sponsors/davidmigloz

topics:
  - ai
  - nlp
  - llms
  - langchain

environment:
  sdk: ">=3.6.0 <4.0.0"
resolution: workspace

dependencies:
  beautiful_soup_dart: ^0.3.0
  cross_file: ^0.3.4+2
  csv: ^6.0.0
  flat_buffers: ^23.5.26
  glob: ^2.1.3
  http: ^1.4.0
  json_path: ^0.7.6
  langchain_core: 0.3.7
  math_expressions: ^3.0.0
  meta: ^1.16.0
  objectbox: ^4.3.0
  path: ^1.9.1
  tavily_dart: ^0.1.1
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.5.1
  langchain_openai: ^0.7.4+2
  objectbox_generator: ^4.3.0
  test: ^1.25.15

objectbox:
  output_dir: src/vector_stores/objectbox
