name: hello_world_backend
description: A sample backend service integrating LangChain.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  langchain: ^0.7.7+2
  langchain_openai: ^0.7.3
  shelf: ^1.4.2
  shelf_router: ^1.1.4
