name: langchain_supabase
description: LangChain.dart integration module for Supabase (e.g. Supabase Vector).
version: 0.1.0
repository: https://github.com/davidmigloz/langchain_dart/tree/main/packages/langchain_supabase
issue_tracker: https://github.com/davidmigloz/langchain_dart/issues?q=label:p:langchain_supabase
homepage: https://github.com/davidmigloz/langchain_dart
documentation: https://langchaindart.com

topics:
  - ai
  - nlp
  - llms
  - langchain
  - vector-db

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.1.0
  langchain_core: ^0.1.0
  meta: ^1.11.0
  supabase: ^2.0.8

dev_dependencies:
  test: ^1.25.2
  langchain: ^0.5.0+1
  langchain_community: 0.1.0
  langchain_openai: ^0.5.0+1
