name: langchain_pinecone
description: LangChain.dart integration module for Pinecone fully-managed vector database.
version: 0.1.0+10
repository: https://github.com/davidmigloz/langchain_dart/tree/main/packages/langchain_pinecone
issue_tracker: https://github.com/davidmigloz/langchain_dart/issues?q=label:p:langchain_pinecone
homepage: https://github.com/davidmigloz/langchain_dart
documentation: https://langchaindart.dev

topics:
  - ai
  - nlp
  - llms
  - langchain
  - vector-db

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  http: ^1.2.2
  langchain_core: 0.3.6
  meta: ^1.11.0
  pinecone: ^0.7.2
  uuid: ^4.5.1

dev_dependencies:
  test: ^1.25.8
  langchain_openai: ^0.7.2+2
