name: docs_examples
description: Examples used in langchaindart.com documentation.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.5

dependencies:
  langchain: ^0.1.0+2
  langchain_openai: ^0.1.1
  langchain_chroma: ^0.1.0+3
