name: docs_examples
description: Examples used in langchaindart.dev documentation.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  langchain: ^0.7.7+1
  langchain_anthropic: ^0.2.0
  langchain_chroma: ^0.2.1+4
  langchain_community: 0.3.2+2
  langchain_google: ^0.6.4+1
  langchain_mistralai: ^0.2.3+1
  langchain_ollama: ^0.3.2+1
  langchain_openai: ^0.7.2+5
