name: docs_examples
description: Examples used in langchaindart.com documentation.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  langchain: ^0.7.0
  langchain_chroma: ^0.2.0+3
  langchain_community: 0.2.0
  langchain_google: ^0.4.0
  langchain_mistralai: ^0.2.0
  langchain_ollama: ^0.2.0
  langchain_openai: ^0.6.0+1
