name: docs_examples
description: Examples used in langchaindart.dev documentation.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  langchain: ^0.7.7
  langchain_anthropic: ^0.1.1+2
  langchain_chroma: ^0.2.1+3
  langchain_community: 0.3.2
  langchain_google: ^0.6.4
  langchain_mistralai: ^0.2.3+1
  langchain_ollama: ^0.3.2
  langchain_openai: ^0.7.2+1
