name: docs_examples
description: Examples used in langchaindart.dev documentation.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"
resolution: workspace

dependencies:
  langchain: ^0.8.1
  langchain_anthropic: ^0.3.1
  langchain_chroma: ^0.3.0+2
  langchain_community: 0.4.0+2
  langchain_google: ^0.7.1
  langchain_mistralai: ^0.3.1
  langchain_ollama: ^0.4.1
  langchain_openai: ^0.8.1
