name: docs_examples
description: Examples used in langchaindart.dev documentation.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  langchain: ^0.7.2
  langchain_chroma: ^0.2.0+5
  langchain_community: 0.2.1+1
  langchain_google: ^0.5.1
  langchain_mistralai: ^0.2.1
  langchain_ollama: ^0.2.2
  langchain_openai: ^0.6.2
