name: langchain_firebase
description: LangChain.dart integration module for Firebase (VertexAI for Firebase, Firestore, etc.).
version: 0.1.0+1
repository: https://github.com/davidmigloz/langchain_dart/tree/main/packages/langchain_firebase
issue_tracker: https://github.com/davidmigloz/langchain_dart/issues?q=label:p:langchain_firebase
homepage: https://github.com/davidmigloz/langchain_dart
documentation: https://langchaindart.dev

topics:
  - ai
  - nlp
  - llms
  - langchain
  - firebase

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  collection: '>=1.17.0 <1.19.0'
  firebase_app_check: ^0.2.2+5
  firebase_core: ^2.31.0
  firebase_vertexai: ^0.1.0
  langchain_core: ^0.3.1
  meta: ^1.11.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
