name: langchain_openai
description: LangChain.dart integration module for OpenAI (GPT-3, GPT-4, Functions, etc.).
version: 0.6.3
repository: https://github.com/davidmigloz/langchain_dart/tree/main/packages/langchain_openai
issue_tracker: https://github.com/davidmigloz/langchain_dart/issues?q=label:p:langchain_openai
homepage: https://github.com/davidmigloz/langchain_dart
documentation: https://langchaindart.dev

topics:
  - ai
  - nlp
  - llms
  - langchain
  - gpt

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: '>=1.17.0 <1.19.0'
  http: ^1.1.0
  langchain_core: 0.3.3
  langchain_tiktoken: ^1.0.1
  meta: ^1.11.0
  openai_dart: ^0.3.3+1
  uuid: ^4.3.3

dev_dependencies:
  langchain: ^0.7.3
  langchain_community: 0.2.2
  test: ^1.25.2
