name: langchain_openai
description: OpenAI module for LangChain.dart.
version: 0.0.3
repository: https://github.com/davidmigloz/langchain_dart/tree/main/packages/langchain_openai
issue_tracker: https://github.com/davidmigloz/langchain_dart/issues
homepage: https://github.com/davidmigloz/langchain_dart
documentation: https://langchaindart.com

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.17.1
  dart_openai: ^4.0.0
  langchain: ^0.0.3
  meta: ^1.9.1
  tiktoken: ^1.0.3

dev_dependencies:
  test: ^1.24.5
