name: langchain_openai
description: LangChain.dart integration module for OpenAI (GPT-5, o3, Embeddings, DALLÂ·E, etc.).
version: 0.8.1+1
repository: https://github.com/davidmigloz/langchain_dart/tree/main/packages/langchain_openai
issue_tracker: https://github.com/davidmigloz/langchain_dart/issues?q=label:p:langchain_openai
homepage: https://github.com/davidmigloz/langchain_dart
documentation: https://langchaindart.dev

funding:
  - https://github.com/sponsors/davidmigloz

topics:
  - nlp
  - gen-ai
  - llms
  - langchain
  - gpt

environment:
  sdk: ">=3.8.0 <4.0.0"
resolution: workspace

dependencies:
  collection: ^1.19.1
  http: ^1.5.0
  langchain_core: 0.4.1
  langchain_tiktoken: ^1.0.1
  meta: ^1.16.0
  openai_dart: ^0.6.2
  uuid: ^4.5.1

dev_dependencies:
  langchain: ^0.8.1
  langchain_community: 0.4.0+2
  test: ^1.26.2
