name: mistralai_dart
description: Dart Client for the Mistral AI API (Mistral-7B, Mixtral 8x7B, embeddings, etc.).
version: 0.0.3+1
repository: https://github.com/davidmigloz/langchain_dart/tree/main/packages/mistralai_dart
issue_tracker: https://github.com/davidmigloz/langchain_dart/issues?q=label:p:mistralai_dart
homepage: https://github.com/davidmigloz/langchain_dart
documentation: https://langchaindart.com

topics:
  - ai
  - nlp
  - llms
  - mistral

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  fetch_client: ^1.0.2
  freezed_annotation: ^2.4.1
  http: ^1.1.0
  json_annotation: ^4.8.1
  meta: ^1.11.0

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  #  openapi_spec: ^0.7.8
  openapi_spec:
    git:
      url: https://github.com/davidmigloz/openapi_spec.git
      ref: e14c0adaac69e9482e9b57f68fc7964032cdd44c
  test: ^1.25.2
