name: browser_summarizer
description: Summarize any webpage with a click of a button!
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  chrome_extension: ^0.4.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  flutter_markdown: ^0.7.7
  langchain: ^0.8.1
  langchain_community: 0.4.0+2
  langchain_openai: ^0.8.1
  shared_preferences: ^2.5.3

flutter:
  uses-material-design: true
