name: browser_summarizer
description: Summarize any webpage with a click of a button!
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  flutter_markdown: ^0.6.22
  js: ^0.7.1
  langchain: ^0.7.3
  langchain_community: 0.2.2
  langchain_openai: ^0.6.3
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true
