name: browser_summarizer
description: Summarize any webpage with a click of a button!
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  flutter_markdown: ^0.7.3
  js: ^0.7.1
  langchain: ^0.7.7+1
  langchain_community: 0.3.2+2
  langchain_openai: ^0.7.2+5
  shared_preferences: ^2.3.0

flutter:
  uses-material-design: true
