name: openai_dart
description: Dart client for the OpenAI API. Supports chat (GPT-4.1, o4-mini, o3, etc.), completions, embeddings, images (gpt-image-1), assistants v2, batch, fine-tuning, etc.
version: 0.5.2
repository: https://github.com/davidmigloz/langchain_dart/tree/main/packages/openai_dart
issue_tracker: https://github.com/davidmigloz/langchain_dart/issues?q=label:p:openai_dart
homepage: https://github.com/davidmigloz/langchain_dart
documentation: https://langchaindart.dev

funding:
  - https://github.com/sponsors/davidmigloz

topics:
  - ai
  - nlp
  - llms
  - gpt

environment:
  sdk: ">=3.6.0 <4.0.0"
resolution: workspace

dependencies:
  freezed_annotation: ^2.4.4
  http: ^1.4.0
  json_annotation: ^4.9.0
  meta: ^1.16.0

dev_dependencies:
  build_runner: ^2.5.1
  freezed: ^2.5.8
  json_serializable: ^6.9.5
#  openapi_spec: ^0.7.8
  openapi_spec:
    git:
      url: https://github.com/davidmigloz/openapi_spec.git
      ref: c99a29b7eaad2d25e7ceb90be56e6a9a41066322
  test: ^1.25.15
