name: openai_dart
description: Dart client for the OpenAI API. Supports chat (GPT-4o, o1, etc.), completions, embeddings, images (DALLÂ·E 3), assistants (threads, vector stores, etc.), batch, fine-tuning, etc.
version: 0.4.4
repository: https://github.com/davidmigloz/langchain_dart/tree/main/packages/openai_dart
issue_tracker: https://github.com/davidmigloz/langchain_dart/issues?q=label:p:openai_dart
homepage: https://github.com/davidmigloz/langchain_dart
documentation: https://langchaindart.dev

topics:
  - ai
  - nlp
  - llms
  - gpt

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  fetch_client: ^1.1.2
  freezed_annotation: ^2.4.2
  http: ^1.2.2
  json_annotation: ^4.9.0
  meta: ^1.11.0

dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^2.5.7
  json_serializable: ^6.8.0
#  openapi_spec: ^0.7.8
  openapi_spec:
    git:
      url: https://github.com/davidmigloz/openapi_spec.git
      ref: 93230a5e346b02789f0f727da8eecea9c7bdf118
  test: ^1.25.8
