name: openai_dart
description: Dart client for the OpenAI API. Supports completions (GPT-3.5 Turbo), chat (GPT-4o, etc.), embeddings (Embedding v3), images (DALLÂ·E 3), assistants v2 (threads, runs, vector stores, etc.) batch, fine-tuning, etc.
version: 0.3.3
repository: https://github.com/davidmigloz/langchain_dart/tree/main/packages/openai_dart
issue_tracker: https://github.com/davidmigloz/langchain_dart/issues?q=label:p:openai_dart
homepage: https://github.com/davidmigloz/langchain_dart
documentation: https://langchaindart.dev

topics:
  - ai
  - nlp
  - llms
  - gpt

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  fetch_client: ^1.0.2
  freezed_annotation: ^2.4.1
  http: ^1.1.0
  json_annotation: ^4.8.1
  meta: ^1.11.0

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.4.7
  json_serializable: ^6.7.1
#  openapi_spec: ^0.7.8
  openapi_spec:
    git:
      url: https://github.com/davidmigloz/openapi_spec.git
      ref: 280ae0d41806eda25e923203d67bd6f4992a81e9
  test: ^1.25.2
