name: hello_world_flutter
description: A sample Flutter app integrating LangChain.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  flutter_markdown: ^0.7.7
  langchain: ^0.8.1
  langchain_google: ^0.7.1
  langchain_mistralai: ^0.3.1+1
  langchain_ollama: ^0.4.1
  langchain_openai: ^0.8.1

flutter:
  uses-material-design: true
