name: hello_world_flutter
description: A sample Flutter app integrating LangChain.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  flutter_markdown: ^0.7.3
  langchain: ^0.7.7+1
  langchain_google: ^0.6.4+1
  langchain_mistralai: ^0.2.3+1
  langchain_ollama: ^0.3.2+1
  langchain_openai: ^0.7.2+5

flutter:
  uses-material-design: true
