name: hello_world_flutter
description: A sample Flutter app integrating LangChain.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  flutter_markdown: ^0.6.22
  langchain: ^0.7.4
  langchain_google: ^0.6.1
  langchain_mistralai: ^0.2.2
  langchain_ollama: ^0.3.0
  langchain_openai: ^0.7.0

flutter:
  uses-material-design: true
