name: vertex_ai
description: GCP Vertex AI ML platform API client (PaLM, Matching Engine, etc.).
version: 0.0.4
repository: https://github.com/davidmigloz/langchain_dart/tree/main/packages/vertex_ai
issue_tracker: https://github.com/davidmigloz/langchain_dart/issues
homepage: https://github.com/davidmigloz/langchain_dart
documentation: https://langchaindart.com

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.17.1
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.1
  http: ^1.1.0
  meta: ^1.9.1

dev_dependencies:
  test: ^1.24.3
