name: vertex_ai
description: GCP Vertex AI ML platform API client (PaLM, Vector Search, etc.).
version: 0.1.0+1
repository: https://github.com/davidmigloz/langchain_dart/tree/main/packages/vertex_ai
issue_tracker: https://github.com/davidmigloz/langchain_dart/issues?q=label:p:vertex_ai
homepage: https://github.com/davidmigloz/langchain_dart
documentation: https://langchaindart.dev

topics:
  - ai
  - nlp
  - llms
  - palm

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  googleapis: ^13.0.0
  googleapis_auth: ^1.6.0
  http: ^1.2.2
  meta: ^1.11.0

dev_dependencies:
  test: ^1.25.8
