name: langchain_chroma
description: LangChain.dart integration module for Chroma open-source embedding database.
version: 0.2.1+5
repository: https://github.com/davidmigloz/langchain_dart/tree/main/packages/langchain_chroma
issue_tracker: https://github.com/davidmigloz/langchain_dart/issues?q=label:p:langchain_chroma
homepage: https://github.com/davidmigloz/langchain_dart
documentation: https://langchaindart.dev

funding:
  - https://github.com/sponsors/davidmigloz

topics:
  - ai
  - nlp
  - llms
  - langchain
  - vector-db

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  chromadb: ^0.2.0+2
  http: ^1.2.2
  langchain_core: 0.3.6+1
  meta: ^1.11.0
  uuid: ^4.5.1

dev_dependencies:
  test: ^1.25.8
  langchain: ^0.7.7+2
  langchain_community: 0.3.3
  langchain_openai: ^0.7.3
