name: langchain_chroma
description: LangChain.dart integration module for Chroma open-source embedding database.
version: 0.2.2
repository: https://github.com/davidmigloz/langchain_dart/tree/main/packages/langchain_chroma
issue_tracker: https://github.com/davidmigloz/langchain_dart/issues?q=label:p:langchain_chroma
homepage: https://github.com/davidmigloz/langchain_dart
documentation: https://langchaindart.dev

funding:
  - https://github.com/sponsors/davidmigloz

topics:
  - ai
  - nlp
  - llms
  - langchain
  - vector-db

environment:
  sdk: ">=3.6.0 <4.0.0"
resolution: workspace

dependencies:
  chromadb: ^0.2.1
  http: ^1.4.0
  langchain_core: 0.3.7
  meta: ^1.16.0
  uuid: ^4.5.1

dev_dependencies:
  test: ^1.25.15
  langchain: ^0.7.8
  langchain_community: 0.3.4
  langchain_openai: ^0.7.4+2
