name: langchain_chroma
description: LangChain.dart integration module for Chroma open-source embedding database.
version: 0.2.0+4
repository: https://github.com/davidmigloz/langchain_dart/tree/main/packages/langchain_chroma
issue_tracker: https://github.com/davidmigloz/langchain_dart/issues?q=label:p:langchain_chroma
homepage: https://github.com/davidmigloz/langchain_dart
documentation: https://langchaindart.com

topics:
  - ai
  - nlp
  - llms
  - langchain
  - vector-db

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  chromadb: ^0.2.0
  http: ^1.1.0
  langchain_core: ^0.3.1
  meta: ^1.11.0
  uuid: ^4.3.3

dev_dependencies:
  test: ^1.25.2
  langchain: ^0.7.1
  langchain_community: 0.2.0+1
  langchain_openai: ^0.6.1+1
