name: langchain_core
description: Contains core abstractions of LangChain.dart and the LangChain Expression Language (LCEL).
version: 0.2.0+1
repository: https://github.com/davidmigloz/langchain_dart/tree/main/packages/langchain_core
issue_tracker: https://github.com/davidmigloz/langchain_dart/issues?q=label:p:langchain_core
homepage: https://github.com/davidmigloz/langchain_dart
documentation: https://langchaindart.com

topics:
  - ai
  - nlp
  - llms
  - langchain

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  async: ^2.11.0
  collection: '>=1.17.0 <1.19.0'
  cross_file: ^0.3.4+1
  crypto: ^3.0.3
  meta: ^1.11.0
  rxdart: ^0.27.7

dev_dependencies:
  test: ^1.25.2
