name: langchain_mistralai
description: LangChain.dart integration module for Mistral AI (Mistral-7B, Mixtral 8x7B, embeddings, etc.).
version: 0.2.3+2
repository: https://github.com/davidmigloz/langchain_dart/tree/main/packages/langchain_mistralai
issue_tracker: https://github.com/davidmigloz/langchain_dart/issues?q=label:p:langchain_mistralai
homepage: https://github.com/davidmigloz/langchain_dart
documentation: https://langchaindart.dev

funding:
  - https://github.com/sponsors/davidmigloz

topics:
  - ai
  - nlp
  - llms
  - langchain
  - mistral

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  http: ^1.2.2
  langchain_core: 0.3.6+1
  langchain_tiktoken: ^1.0.1
  meta: ^1.11.0
  mistralai_dart: ^0.0.3+4

dev_dependencies:
  test: ^1.25.8
