name: langchain_mistralai
description: LangChain.dart integration module for Mistral AI (Mistral-7B, Mixtral 8x7B, embeddings, etc.).
version: 0.2.4+3
repository: https://github.com/davidmigloz/langchain_dart/tree/main/packages/langchain_mistralai
issue_tracker: https://github.com/davidmigloz/langchain_dart/issues?q=label:p:langchain_mistralai
homepage: https://github.com/davidmigloz/langchain_dart
documentation: https://langchaindart.dev

funding:
  - https://github.com/sponsors/davidmigloz

topics:
  - ai
  - nlp
  - llms
  - langchain
  - mistral

environment:
  sdk: ">=3.6.0 <4.0.0"
resolution: workspace

dependencies:
  collection: ^1.19.1
  http: ^1.5.0
  langchain_core: 0.3.9
  langchain_tiktoken: ^1.0.1
  meta: ^1.16.0
  mistralai_dart: ^0.0.6

dev_dependencies:
  langchain: ^0.7.9
  test: ^1.26.2
