name: anthropic_sdk_dart
description: Dart Client for the Anthropic API (Claude 3.5 Sonnet, Opus, Haiku, etc.).
version: 0.1.0
repository: https://github.com/davidmigloz/langchain_dart/tree/main/packages/anthropic_sdk_dart
issue_tracker: https://github.com/davidmigloz/langchain_dart/issues?q=label:p:anthropic_sdk_dart
homepage: https://github.com/davidmigloz/langchain_dart
documentation: https://langchaindart.dev

topics:
  - ai
  - nlp
  - llms
  - anthropic

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  fetch_client: ^1.0.2
  freezed_annotation: ^2.4.1
  http: ^1.1.0
  json_annotation: ^4.8.1
  meta: ^1.11.0

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  #  openapi_spec: ^0.7.8
  openapi_spec:
    git:
      url: https://github.com/davidmigloz/openapi_spec.git
      ref: 280ae0d41806eda25e923203d67bd6f4992a81e9
  test: ^1.25.2
