name: wikivoyage_eu
description: Wikivoyage EU chatbot using llama3.2 and ObjectBox.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  langchain: ^0.7.7+1
  langchain_ollama: ^0.3.2+1
  langchain_community: 0.3.2+1
