name: chromadb
description: Dart Client for the Chroma open-source embedding database API.
version: 0.0.3
repository: https://github.com/davidmigloz/langchain_dart/tree/main/packages/chromadb
issue_tracker: https://github.com/davidmigloz/langchain_dart/issues
homepage: https://github.com/davidmigloz/langchain_dart
documentation: https://langchaindart.com

topics:
  - ai
  - nlp
  - vector-db

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  freezed_annotation: ^2.4.1
  http: ^1.1.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  openapi_spec: ^0.5.0
  test: ^1.24.3
