name: langchain_ollama
description: LangChain.dart integration module for Ollama (run Llama 3.2, Gemma 2, Phi-3.5, Mistral nemo, Qwen2 and other models locally).
version: 0.3.2+2
repository: https://github.com/davidmigloz/langchain_dart/tree/main/packages/langchain_ollama
issue_tracker: https://github.com/davidmigloz/langchain_dart/issues?q=label:p:langchain_ollama
homepage: https://github.com/davidmigloz/langchain_dart
documentation: https://langchaindart.dev

topics:
  - ai
  - nlp
  - llms
  - langchain
  - ollama

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  http: ^1.2.2
  langchain_core: 0.3.6+1
  langchain_tiktoken: ^1.0.1
  meta: ^1.11.0
  ollama_dart: ^0.2.2+1
  uuid: ^4.5.1

dev_dependencies:
  test: ^1.25.8
