name: langchain_ollama
description: LangChain.dart integration module for Ollama (run Llama 2, Mistral, Vicuna and other models locally).
version: 0.2.0
repository: https://github.com/davidmigloz/langchain_dart/tree/main/packages/langchain_ollama
issue_tracker: https://github.com/davidmigloz/langchain_dart/issues?q=label:p:langchain_ollama
homepage: https://github.com/davidmigloz/langchain_dart
documentation: https://langchaindart.com

topics:
  - ai
  - nlp
  - llms
  - langchain
  - ollama

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: '>=1.17.0 <1.19.0'
  http: ^1.1.0
  langchain_core: ^0.3.0
  langchain_tiktoken: ^1.0.1
  meta: ^1.11.0
  ollama_dart: ^0.0.3+1
  uuid: ^4.3.3

dev_dependencies:
  test: ^1.25.2
