name: langchain_ollama
description: LangChain.dart integration module for Ollama (run Llama 4, Gemma 3, Phi4, Mistral, Qwen3 and other models locally).
version: 0.3.3+3
repository: https://github.com/davidmigloz/langchain_dart/tree/main/packages/langchain_ollama
issue_tracker: https://github.com/davidmigloz/langchain_dart/issues?q=label:p:langchain_ollama
homepage: https://github.com/davidmigloz/langchain_dart
documentation: https://langchaindart.dev

funding:
  - https://github.com/sponsors/davidmigloz

topics:
  - nlp
  - gen-ai
  - llms
  - langchain
  - ollama

environment:
  sdk: ">=3.8.0 <4.0.0"
resolution: workspace

dependencies:
  collection: ^1.19.1
  http: ^1.5.0
  langchain_core: 0.3.9
  langchain_tiktoken: ^1.0.1
  meta: ^1.16.0
  ollama_dart: ^0.2.5
  uuid: ^4.5.1

dev_dependencies:
  langchain: ^0.7.9
  test: ^1.26.2
