name: openai_realtime_dart
description: Dart client for the OpenAI Realtime API (beta), a stateful, event-based API that communicates over a WebSocket.
version: 0.0.4
repository: https://github.com/davidmigloz/langchain_dart/tree/main/packages/openai_realtime_dart
issue_tracker: https://github.com/davidmigloz/langchain_dart/issues?q=label:p:openai_realtime_dart
homepage: https://github.com/davidmigloz/langchain_dart
documentation: https://langchaindart.dev

funding:
  - https://github.com/sponsors/davidmigloz

topics:
  - ai
  - llms
  - openai

environment:
  sdk: ">=3.6.0 <4.0.0"
resolution: workspace

dependencies:
  freezed_annotation: ^2.4.4
  http: ^1.4.0
  json_annotation: ^4.9.0
  logging: ^1.3.0
  web_socket_channel: ^3.0.2

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^2.5.8
  json_serializable: ^6.9.5
  openapi_spec:
    git:
      url: https://github.com/davidmigloz/openapi_spec.git
      ref: c99a29b7eaad2d25e7ceb90be56e6a9a41066322
  test: ^1.25.15
