name: openai_realtime_dart
description: Dart client for the OpenAI Realtime API (beta), a stateful, event-based API that communicates over a WebSocket.
version: 0.1.0
repository: https://github.com/davidmigloz/langchain_dart/tree/main/packages/openai_realtime_dart
issue_tracker: https://github.com/davidmigloz/langchain_dart/issues?q=label:p:openai_realtime_dart
homepage: https://github.com/davidmigloz/langchain_dart
documentation: https://langchaindart.dev

funding:
  - https://github.com/sponsors/davidmigloz

topics:
  - ai
  - llms
  - openai

environment:
  sdk: ">=3.8.0 <4.0.0"
resolution: workspace

dependencies:
  freezed_annotation: ^3.1.0
  http: ^1.5.0
  json_annotation: ^4.9.0
  logging: ^1.3.0
  web_socket_channel: ^3.0.2

dev_dependencies:
  build_runner: ^2.5.4
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  openapi_spec:
    git:
      url: https://github.com/davidmigloz/openapi_spec.git
      ref: 4fbc3c3841faf90c6799cb6d871a4f3b0ef82624
  test: ^1.26.2
